project_name: capitano

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - id: build_cgo
    main: ./
    binary: capitano
    ldflags:
      - -s -w -X github.com/maietta/capitano.Version={{ .Version }}
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

  - id: build_noncgo
    main: ./
    binary: capitano
    ldflags:
      - -s -w -X github.com/maietta/capitano.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

release:
  draft: true

archives:
  - id: archive_cgo
    builds: [build_cgo]
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_cgo'
    format: binary
    files:
      - LICENSE*
      - CHANGELOG*

  - id: archive_noncgo
    builds: [build_noncgo]
    format: binary
    # files:
    #   - LICENSE*
    #   - CHANGELOG*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'
      - '^ui:'